#!/usr/bin/env bash
# Capture HTTPS payloads from a VS Code instance launched through mitmproxy.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MITM_ADDON="$SCRIPT_DIR/mitm_bridge.py"
NODE_LOGGER="$SCRIPT_DIR/payload_logger.js"

MITM_PORT=19473
OUTPUT_FILE="vscode-traffic-$(date +%Y%m%d-%H%M%S).jsonl"
MITM_LOG=""
WORKSPACE=""
APP_PATH="/Applications/Visual Studio Code.app"
USER_DATA_DIR=""
EXTENSIONS_DIR=""
LAUNCH=true
IGNORE_CERT_ERRORS=true

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  -o, --output          JSONL payload log file              (default: vscode-traffic-<timestamp>.jsonl)
  --mitm-log           mitmdump console log file            (default: <output>.mitm.log)
  --port               Local mitmproxy port                 (default: 19473)
  --workspace          Workspace folder/file to open
  --app-path           VS Code .app path                    (default: /Applications/Visual Studio Code.app)
  --user-data-dir      VS Code user data dir                (default: temporary isolated dir)
  --extensions-dir     VS Code extensions dir
  --no-launch          Start proxy only and print launch environment
  --strict-certs       Do not pass --ignore-certificate-errors to VS Code
  -h, --help           Show this help

Examples:
  $(basename "$0") --workspace /path/to/project -o vscode.jsonl
  $(basename "$0") --no-launch -o vscode.jsonl
EOF
  exit 0
}

log() { echo "[$(date '+%H:%M:%S')] $*"; }
err() { echo "[ERROR] $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output) OUTPUT_FILE="$2"; shift 2 ;;
    --mitm-log) MITM_LOG="$2"; shift 2 ;;
    --port) MITM_PORT="$2"; shift 2 ;;
    --workspace) WORKSPACE="$2"; shift 2 ;;
    --app-path) APP_PATH="$2"; shift 2 ;;
    --user-data-dir) USER_DATA_DIR="$2"; shift 2 ;;
    --extensions-dir) EXTENSIONS_DIR="$2"; shift 2 ;;
    --no-launch) LAUNCH=false; shift ;;
    --strict-certs) IGNORE_CERT_ERRORS=false; shift ;;
    -h|--help) usage ;;
    *) err "Unknown option: $1. Use -h for help." ;;
  esac
done

command -v mitmdump &>/dev/null || err "mitmdump not found. Install it with: brew install mitmproxy"
command -v node &>/dev/null || err "node not found. Install Node.js before using this monitor."

if [[ -z "$MITM_LOG" ]]; then
  MITM_LOG="$OUTPUT_FILE.mitm.log"
fi

if [[ -z "$USER_DATA_DIR" ]]; then
  USER_DATA_DIR="$(mktemp -d "${TMPDIR:-/tmp}/traffic-hunt-vscode.XXXXXX")"
fi

CODE_BIN="$APP_PATH/Contents/MacOS/Electron"
if [[ "$LAUNCH" == true && ! -x "$CODE_BIN" ]]; then
  err "VS Code executable not found at: $CODE_BIN. Pass --app-path if VS Code is installed elsewhere."
fi

PROXY_URL="http://127.0.0.1:$MITM_PORT"
MITM_CA="$HOME/.mitmproxy/mitmproxy-ca-cert.pem"

cleanup() {
  if [[ -n "${MITM_PID:-}" ]]; then
    kill "$MITM_PID" 2>/dev/null || true
    wait "$MITM_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

log "Mode:       VS Code HTTPS interception"
log "Proxy:      $PROXY_URL"
log "Payloads:   $OUTPUT_FILE"
log "mitmdump:   $MITM_LOG"
log "User data:  $USER_DATA_DIR"

mitmdump \
  --listen-host 127.0.0.1 \
  --listen-port "$MITM_PORT" \
  --set "payload_log=$OUTPUT_FILE" \
  --set "node_logger=$NODE_LOGGER" \
  -s "$MITM_ADDON" \
  --flow-detail 1 \
  >"$MITM_LOG" 2>&1 &
MITM_PID=$!

sleep 1
if ! kill -0 "$MITM_PID" 2>/dev/null; then
  err "mitmdump failed to start. Check: $MITM_LOG"
fi

echo ""
echo "Proxy environment:"
echo "  HTTP_PROXY=$PROXY_URL"
echo "  HTTPS_PROXY=$PROXY_URL"
echo "  ALL_PROXY=$PROXY_URL"
echo "  NODE_EXTRA_CA_CERTS=$MITM_CA"
echo "  SSL_CERT_FILE=$MITM_CA"
echo "  REQUESTS_CA_BUNDLE=$MITM_CA"
echo "  CURL_CA_BUNDLE=$MITM_CA"
echo ""

if [[ ! -f "$MITM_CA" ]]; then
  log "mitmproxy CA not found yet at $MITM_CA. It should be generated by this run."
fi

if [[ "$LAUNCH" == false ]]; then
  log "Proxy is running. Launch VS Code or a child process with the environment above."
  log "Press Ctrl+C to stop."
  wait "$MITM_PID"
  exit 0
fi

CODE_ARGS=(
  "--user-data-dir=$USER_DATA_DIR"
  "--proxy-server=$PROXY_URL"
)

if [[ "$IGNORE_CERT_ERRORS" == true ]]; then
  CODE_ARGS+=("--ignore-certificate-errors")
fi

if [[ -n "$EXTENSIONS_DIR" ]]; then
  CODE_ARGS+=("--extensions-dir=$EXTENSIONS_DIR")
fi

if [[ -n "$WORKSPACE" ]]; then
  CODE_ARGS+=("$WORKSPACE")
fi

log "Launching: $CODE_BIN ${CODE_ARGS[*]}"

HTTP_PROXY="$PROXY_URL" \
HTTPS_PROXY="$PROXY_URL" \
ALL_PROXY="$PROXY_URL" \
http_proxy="$PROXY_URL" \
https_proxy="$PROXY_URL" \
all_proxy="$PROXY_URL" \
NODE_EXTRA_CA_CERTS="$MITM_CA" \
SSL_CERT_FILE="$MITM_CA" \
REQUESTS_CA_BUNDLE="$MITM_CA" \
CURL_CA_BUNDLE="$MITM_CA" \
GLOBAL_AGENT_HTTP_PROXY="$PROXY_URL" \
GLOBAL_AGENT_HTTPS_PROXY="$PROXY_URL" \
npm_config_proxy="$PROXY_URL" \
npm_config_https_proxy="$PROXY_URL" \
"$CODE_BIN" "${CODE_ARGS[@]}" &
CODE_PID=$!

log "VS Code PID: $CODE_PID"
log "Press Ctrl+C to stop capture."
wait "$MITM_PID"
